-- MySQL Script generated by MySQL Workbench
-- Sun May 20 18:08:07 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autores` (
  `id_autor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido_m` VARCHAR(45) NULL,
  `apellido_p` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  PRIMARY KEY (`id_autor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`editoriales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`editoriales` (
  `id_editorial` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `pagina` VARCHAR(45) NULL,
  PRIMARY KEY (`id_editorial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`temas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`temas` (
  `id_tema` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`libros` (
  `id_libros` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `anio` VARCHAR(45) NULL,
  `idioma` VARCHAR(45) NULL,
  `id_autor` INT NOT NULL,
  `id_editorial` INT NULL,
  `id_tema` INT NULL,
  `disponibles` INT NOT NULL,
  `precio` FLOAT NOT NULL,
  `imagen` VARCHAR(45) NULL,
  PRIMARY KEY (`id_libros`),
  INDEX `id_autor_idx` (`id_autor` ASC),
  INDEX `id_editorial_idx` (`id_editorial` ASC),
  INDEX `fk_tema_idx` (`id_tema` ASC),
  CONSTRAINT `fk_autor`
    FOREIGN KEY (`id_autor`)
    REFERENCES `mydb`.`autores` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_editorial`
    FOREIGN KEY (`id_editorial`)
    REFERENCES `mydb`.`editoriales` (`id_editorial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tema`
    FOREIGN KEY (`id_tema`)
    REFERENCES `mydb`.`temas` (`id_tema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `nombre` VARCHAR(45) NOT NULL,
  `apellido_p` VARCHAR(45) NOT NULL,
  `apellido_m` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `tarjeta` VARCHAR(45) NULL,
  `direccion` VARCHAR(300) NULL,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carrito` (
  `id_venta` INT NOT NULL AUTO_INCREMENT,
  `id_libro` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `total` FLOAT NULL,
  `fecha` DATE NULL,
  `flag` TINYINT NULL,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_venta`),
  INDEX `fk_idlibro_idx` (`id_libro` ASC),
  INDEX `fk_username_idx` (`username` ASC),
  CONSTRAINT `fk_idlibro`
    FOREIGN KEY (`id_libro`)
    REFERENCES `mydb`.`libros` (`id_libros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_username`
    FOREIGN KEY (`username`)
    REFERENCES `mydb`.`clientes` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'admin' IDENTIFIED BY 'admin';

GRANT ALL ON `mydb`.* TO 'admin';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
